### PR TITLE
Increase _verify_mount_point limit

### PR DESCRIPTION
**Pull request by juhhov**
Odroid C2 mount point reappearing takes constantly ~12 seconds.
Increase the limit from 10 to 20 seconds.

### CODE REVIEW

**Comment by jonikula** [comment]
Is this related to the issue we discussed yesterday?

**Comment by juhhov** [comment]
Yes, at least from ldm + odroid point of view.

**Comment by RomanSaveljev** [comment]
Why ldm takes more time to create mount points?

**Comment by juhhov** [comment]
@RomanSaveljev isn't this the same thing you created a fix for raas-daemon? Of course this should be looked more closely especially if odroid becomes more popular.

**Comment by RomanSaveljev** [comment]
so, please look

**Comment by juhhov** [comment]
Even pylint is happy. Merging..

**Pull request merged**
