### PR TITLE
CI: add linux-nuc

### PR DESCRIPTION
**Pull request by YifeiZuo01**
## Status
**READY**

## Description
pi3 is experiencing some Hudson exception. Thus, it cannot be used to verify Linux test result and need manually verification.

Bring up Linux-nuc to run test case would help this situation.

Changes:

1.Previsouly linux github status label renamed to Rpi3
2. New linux-nuc github status label. and pylient check runs on this nuc.

## Todo
- [x] fix testcase

### CODE REVIEW

**Comment by YifeiZuo01** [comment]
There is a decision to make about [one test case](https://github.com/ARMmbed/mbed-flasher/blob/master/test/hardware/test_erase.py#L55), it failed on linux-nuc because of nuc has Jlink board connected, and this use target_id 'all'.

**Comment by jupe** [comment]
why nuc test fails ?

**Comment by YifeiZuo01** [comment]
"Required" need to be removed from these pending labels.

linux py2 test Expected — Waiting for status to be reported           Required
linux py3 test Expected — Waiting for status to be reported           Required

**Comment by jupe** [comment]
> skip this tests case?

yes. Lets skip it but add mention why it is skipped -> require that all boards connected supports erase - which are not the case now..

**Pull request merged**
