### PR TITLE
read also lower-case mbed.htm

### PR DESCRIPTION
**Pull request by jupe**
This fix at least NUC472 timeout issue where flasher waits file `.HTM` even in this case it was `.htm`. There is probably another similar issues here as well.

### CODE REVIEW

**Comment by ErkkiMehtala** [comment]
LGTM

**Comment by jupe** [comment]
this seems to fix NUC472 issue

**Comment by RomanSaveljev** [comment]
Can we finalize this fix?

**Comment by juhhov** [comment]
@VeliMattiLahtela have a look

**Pull request merged**
