### PR TITLE
Py3 support

### PR DESCRIPTION
**Pull request by YifeiZuo01**
## Status
**IN DEVELOPMENT**

## Description
Bring python3 support for mbed-flasher

## Relates to
* mbed-clitest - [py3 support](https://github.com/ARMmbed/mbed-clitest/pull/760) --Ready
* mbed-ls - [fix](https://github.com/ARMmbed/mbed-ls/pull/180)

### CODE REVIEW

**Comment by YifeiZuo01** [comment]
Test all the CLI (single, all, prefix, verbose, pyocd):
* Flash 
* Erase
* Reset

Failed case:  flash, erase and reset with `pyocd`.
WIP.

**Comment by YifeiZuo01** [comment]
For my environment: 
* py2: pyocd doesn't work with mbed-flasher.
* py3: pyocd doesn't work with mbed-flasher.

**Comment by jupe** [comment]
@VeliMattiLahtela could you try this also ?

**Comment by jupe** [comment]
@YifeiZuo01 please create PR for mbed-ls which fix major issue with python3.

**Comment by YifeiZuo01** [comment]
@jupe  could you help check if I have access right to push to mbed-ls?

**Comment by YifeiZuo01** [comment]
@VeliMattiLahtela  could you please check once more if it works now and if there are any other problems?

**Comment by YifeiZuo01** [comment]
@jupe  Are we going to merge this, since Vellu has double checked it's fine?

**Pull request merged**
