### PR TITLE
Win space in path support

### PR DESCRIPTION
**Pull request by ErkkiMehtala**
For review @jonikula @juhhov @VeliMattiLahtela. 

This was tested in path with and without spaces.

### CODE REVIEW

**Comment by jonikula** [comment]
Should this PR be finalized and added to the next release as well? @ErkkiMehtala @VeliMattiLahtela

**Comment by RomanSaveljev** [comment]
@ErkkiMehtala please fix merge conflicts

**Comment by ErkkiMehtala** [comment]
Yep, this has been hanging in review so long time no surprice there has been some changes:)

**Comment by jupe** [comment]
replaced with #90

**Pull request closed without merging**
